mysql:
  host: 35.240.161.144
  user: vunv
  passwd: Vu@1479825
  db: hook_processing

mqtt:
  host: 35.240.161.144
  port:
    tcp: 1883
    websocket: 8000
    broker: 8080

cli:
  question:
    type: list
    name: choice
    message: What do you want connect to Hook Processing server ?
    choices:
      - "Yes"
      - "No"
use_anonymous: True,
