mysql:
  host: localhost
  user: root
  passwd:
  db: hook_processing

cli:
  question:
    type: list
    name: choice
    message: What do you want connect to Hook Processing server ?
    choices:
      - 'Yes'
      - 'No'
use_anonymous: True,
